# 环境信息

BASE: 
  # log等级
  log_level: "debug"
  # 扩展名
  log_extension: '.log'
  test: 
    url: 'https://www.baidu.com'
    case_file: 'test_data.xlsx'
    case_sheet: '接口测试用例_1'

Email:
  email_host: 'smtp.qq.com'
  sender: ''
  auth_code: ''
  to_recv: []
  cc_recv: []