# 编写相关信息
msdb1:
  db_host: 'localhost'
  db_user: 'root'
  db_passwd: '123456'
  db_database: 'test'
  db_port: 3306
  db_charset: 'utf8'

msdb2:
  db_host: 'localhost'
  db_user: 'admin'
  db_passwd: 4321
  db_database: 'test_db'
  db_port: 1111
  db_charset: 'utf8'

mgdb1:
  db_uri: ''
  db_pboc: ''