# 环境信息

BASE: 
  # log等级
  log_level: "debug"
  # 扩展名
  log_extension: '.log'
  test: 
    # url: 'https://www.baidu.com'
    test_case:  'test_case.xlsx'
    case_sheet: '接口测试用例_1'
    test_data:  'test_data.xlsx'
    data_sheet: '测试用户_1'

Email:
  email_host: 'smtp.qq.com'
  sender: ''
  auth_code: ''
  to_recv: []
  cc_recv: []