# 环境信息

BASE: 
  # log等级
  log_level: "debug"
  # 扩展名
  log_extension: '.log'
  test: 
    # url: 'https://www.baidu.com'
    test_case:  'test_case.xlsx'
    case_sheet: '接口测试用例_1'
    test_data:  'test_data.xlsx'
    data_sheet: '测试用户_1'

Email:
  email_host: 'smtp.qq.com'
  sender: '断浪<mrwindseeker@qq.com>'
  auth_code: 'pqcfuvlmdiubbhcb'
  to_recv: ['聂风<mrwindseeker@me.com>','秦霜<mrwindseeker@163.com>']
  cc_recv: ['断浪<mrwindseeker@qq.com>']